# Form implementation generated from reading ui file '.\resources\views\scroll_part.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(806, 300)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(450, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("QWidget{\n"
"    border-radius: 35px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel\n"
"{\n"
"    color: rgb(59, 59, 59);\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.given_answ = QtWidgets.QLabel(self.widget)
        self.given_answ.setStyleSheet("")
        self.given_answ.setWordWrap(True)
        self.given_answ.setObjectName("given_answ")
        self.gridLayout.addWidget(self.given_answ, 1, 1, 1, 1)
        self.right_answ = QtWidgets.QLabel(self.widget)
        self.right_answ.setStyleSheet("")
        self.right_answ.setWordWrap(True)
        self.right_answ.setObjectName("right_answ")
        self.gridLayout.addWidget(self.right_answ, 2, 1, 1, 1)
        self.question = QtWidgets.QLabel(self.widget)
        self.question.setStyleSheet("")
        self.question.setWordWrap(True)
        self.question.setObjectName("question")
        self.gridLayout.addWidget(self.question, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.given_answ.setText(_translate("Form", "Pergjigja juaj:"))
        self.right_answ.setText(_translate("Form", "Pergjigja e sakte:"))
        self.question.setText(_translate("Form", "Pyetja:"))
